[[session]]
name = "ğŸ¤ kw"
path = "~/ghq/github.com/knowledge-work/knowledgework"

[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "ls"
preview_command = "ls -l"

[[session]]
name = "tmux"
path = "~/dotfiles/tmux"
startup_command = "nvim .tmux.conf"

[[session]]
name = "ğŸ˜ˆ nvim"
path = "~/dotfiles/nvim"
startup_command = "nvim lua/plugins.lua"

[[session]]
name = "ğŸ’» karabiner"
path = "~/dotfiles/karabiner"
startup_command = "nvim ."

[[session]]
name = "ğŸ’§ aqua"
path = "~/dotfiles/aqua"
startup_command = "nvim aqua.yaml"

[[session]]
name = "ğŸ“ sesh"
path = "~/dotfiles/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "ğŸ’¬ dotfiles"
path = "~/dotfiles"
startup_command = "dotfiles link && nvim ."
windows = ["git", "echo"]

[[session]]
name = "ğŸ§¢ zsh"
path = "~/dotfiles"
startup_command = "vim -p .zshrc zsh/alias.zsh"

[[session]]
name = "ğŸ® wezterm"
path = "~/dotfiles/wezterm"
startup_command = "vim wezterm.lua"

[[session]]
name = "ğŸ‘¨â€ğŸ”§ me"
path = "~/junk"

[[session]]
name = "â˜ï¸ floax"

[[session]]
name = "ğŸ¤š kos"
path = "~/ghq/github.com/KOS-LLC/ai-dev-ops"

[[session]]
name = "spotify"
path = "~/"
startup_command = "spotify_player"

[[window]]
name = "git"
startup_script = "git pull"

[[window]]
name = "echo"
startup_script = "echo 'Hello, World!'"
