[[session]]
name = "ğŸ¤kw"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "ğŸ“¥Downloads"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "ğŸ“„tmux"
path = "~/dotfiles/tmux"
startup_command = "nvim .tmux.conf"

[[session]]
name = "ğŸ˜ˆnvim"
path = "~/dotfiles/nvim"
startup_command = "nvim lua/plugins.lua"

[[session]]
name = "ğŸ’»karabiner"
path = "~/dotfiles/karabiner"
startup_command = "nvim ."

[[session]]
name = "ğŸ’§aqua"
path = "~/dotfiles/aqua"
startup_command = "nvim aqua.yaml"

[[session]]
name = "ğŸ“sesh"
path = "~/dotfiles/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "ğŸ’¬dotfiles"
path = "~/dotfiles"
startup_command = "dotfiles link && nvim ."
